<a href="https://colab.research.google.com/github/GenFPS/Algorithms-for-data-science/blob/main/TSP_realization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ACO TSP

In [ ]:
import numpy as np
import random as rd
import time

Для 5 городов

In [ ]:
def lengthCal(antPath, distance_matrix_5):         # Рассчитать расстояние
    length =[]
    dis = 0
    for i in range(len(antPath)):
        for j in range(len(antPath[i]) - 1):
            dis += distance_matrix_5[antPath[i][j]][antPath[i][j + 1]]
        dis += distance_matrix_5[antPath[i][-1]][antPath[i][0]]
        length.append(dis)
        dis = 0
    return length

distance_matrix_5 = np.array([[0, 38, 74, 59, 45],
                            [38, 0, 46, 61, 72],
                            [74, 46, 0, 49, 85],
                            [59, 61, 49, 0, 42],
                            [45, 72, 85, 42, 0]])

antNum = 2                   # кол-во муравьев
alpha = 1                     # Фактор важности феромона
beta = 4                      # Фактор важности эвристической функции
pheEvaRate = 0.1              # Скорость испарения феромона
cityNum = distance_matrix_5.shape[0]
pheromone = np.ones((cityNum, cityNum))                   # Матрица феромонов
heuristic = 1 / (np.eye(cityNum) + distance_matrix_5) - np.eye(cityNum)       # Матрица эвристической информации
iter,itermax = 1, 100                       # Итерации

start_time = time.time()

while iter < itermax:
    antPath = np.zeros((antNum, cityNum)).astype(int) - 1   # Путь муравья
    firstCity = [i for i in range(5)]
    rd.shuffle(firstCity)          # Случайно назначьте начальный город для каждого муравья
    unvisted = []
    p = []
    pAccum = 0
    for i in range(len(antPath)):
        antPath[i][0] = firstCity[i]
    for i in range(len(antPath[0]) - 1): # Постепенное обновление следующего города, в который собирается каждый муравей
        for j in range(len(antPath)):
            for k in range(cityNum):
                if k not in antPath[j]:
                    unvisted.append(k)
            for m in unvisted:
                pAccum += pheromone[antPath[j][i]][m] ** alpha * heuristic[antPath[j][i]][m] ** beta
            for n in unvisted:
                p.append(pheromone[antPath[j][i]][n] ** alpha * heuristic[antPath[j][i]][n] ** beta / pAccum)
            roulette = np.array(p).cumsum()               # Создать рулетку
            r = rd.uniform(min(roulette), max(roulette))
            for x in range(len(roulette)):
                if roulette[x] >= r:                      # Используйте метод рулетки, чтобы выбрать следующий город
                    antPath[j][i + 1] = unvisted[x]
                    break
            unvisted = []
            p = []
            pAccum = 0
    pheromone = (1 - pheEvaRate) * pheromone            # Феромон летучий
    length = lengthCal(antPath, distance_matrix_5)
    for i in range(len(antPath)):
        for j in range(len(antPath[i]) - 1):
            pheromone[antPath[i][j]][antPath[i][j + 1]] += 1 / length[i]     # Обновление феромона
        pheromone[antPath[i][-1]][antPath[i][0]] += 1 / length[i]
    iter += 1

print("Кратчайшее расстояние (в км): ")
print(min(length))
print("Самый короткий путь:")
print(antPath[length.index(min(length))])
print("Время выполнения:", (time.time() - start_time)) # вычисление времени выполнения

Кратчайшее расстояние (в км): 
220
Самый короткий путь:
[1 2 3 4 0]
Время выполнения: 0.04230928421020508


Для 8 городов

In [ ]:
def lengthCal(antPath, distance_matrix_8):         # Рассчитать расстояние
    length =[]
    dis = 0
    for i in range(len(antPath)):
        for j in range(len(antPath[i]) - 1):
            dis += distance_matrix_8[antPath[i][j]][antPath[i][j + 1]]
        dis += distance_matrix_8[antPath[i][-1]][antPath[i][0]]
        length.append(dis)
        dis = 0
    return length


distance_matrix_8 = np.array([[0, 38, 74, 59, 45, 47, 90, 25],
                               [38, 0, 46, 61, 72, 50, 43, 51],
                               [74, 46, 0, 49, 85, 54, 59, 69],
                               [59, 61, 49, 0, 42, 35, 47, 56],
                               [45, 72, 85, 42, 0, 35, 47, 56],
                               [47, 50, 54, 35, 66, 0, 36, 44],
                               [90, 43, 59, 47, 35, 36, 0, 56],
                               [25, 51, 69, 56, 48, 44, 56, 0]])


antNum = 8                    # кол-во муравьев
alpha = 1                     # Фактор важности феромона
beta = 4                      # Фактор важности эвристической функции
pheEvaRate = 0.1              # Скорость испарения феромона
cityNum = distance_matrix_8.shape[0]
pheromone = np.ones((cityNum, cityNum))                   # Матрица феромонов
heuristic = 1 / (np.eye(cityNum) + distance_matrix_8) - np.eye(cityNum)       # Матрица эвристической информации
iter,itermax = 1, 100                       # Итерации

start_time = time.time()

while iter < itermax:
    antPath = np.zeros((antNum, cityNum)).astype(int) - 1   # Путь муравья
    firstCity = [i for i in range(8)]
    rd.shuffle(firstCity)          # Случайно назначьте начальный город для каждого муравья
    unvisted = []
    p = []
    pAccum = 0
    for i in range(len(antPath)):
        antPath[i][0] = firstCity[i]
    for i in range(len(antPath[0]) - 1):       # Постепенное обновление следующего города, в который собирается каждый муравей
        for j in range(len(antPath)):
            for k in range(cityNum):
                if k not in antPath[j]:
                    unvisted.append(k)
            for m in unvisted:
                pAccum += pheromone[antPath[j][i]][m] ** alpha * heuristic[antPath[j][i]][m] ** beta
            for n in unvisted:
                p.append(pheromone[antPath[j][i]][n] ** alpha * heuristic[antPath[j][i]][n] ** beta / pAccum)
            roulette = np.array(p).cumsum()               # Создать рулетку
            r = rd.uniform(min(roulette), max(roulette))
            for x in range(len(roulette)):
                if roulette[x] >= r:                      # Используйте метод рулетки, чтобы выбрать следующий город
                    antPath[j][i + 1] = unvisted[x]
                    break
            unvisted = []
            p = []
            pAccum = 0
    pheromone = (1 - pheEvaRate) * pheromone            # Феромон летучий
    length = lengthCal(antPath, distance_matrix_8)
    for i in range(len(antPath)):
        for j in range(len(antPath[i]) - 1):
            pheromone[antPath[i][j]][antPath[i][j + 1]] += 1 / length[i]     # Обновление феромона
        pheromone[antPath[i][-1]][antPath[i][0]] += 1 / length[i]
    iter += 1
print("Кратчайшее расстояние (в км): ")
print(min(length))
print("Самый короткий путь:")
print(antPath[length.index(min(length))])
print("Время выполнения:", (time.time() - start_time)) # вычисление времени выполнения

Кратчайшее расстояние (в км): 
332
Самый короткий путь:
[0 7 4 5 3 2 6 1]
Время выполнения: 0.3322625160217285


Для 10 городов

In [ ]:
def lengthCal(antPath, distance_matrix_10):         # Рассчитать расстояние
    length =[]
    dis = 0
    for i in range(len(antPath)):
        for j in range(len(antPath[i]) - 1):
            dis += distance_matrix_10[antPath[i][j]][antPath[i][j + 1]]
        dis += distance_matrix_10[antPath[i][-1]][antPath[i][0]]
        length.append(dis)
        dis = 0
    return length

distance_matrix_10 = np.array([[0, 38, 74, 59, 45, 47, 90, 25, 67, 84],
                               [38, 0, 46, 61, 72, 50, 43, 51, 62, 45],
                               [74, 46, 0, 49, 85, 54, 59, 69, 40, 44],
                               [59, 61, 49, 0, 42, 35, 47, 56, 24, 35],
                               [45, 72, 85, 42, 0, 35, 47, 56, 24, 50],
                               [47, 50, 54, 35, 66, 0, 36, 44, 37, 80],
                               [90, 43, 59, 47, 35, 36, 0, 56, 63, 51],
                               [25, 51, 69, 56, 48, 44, 56, 0, 71, 60],
                               [67, 62, 70, 24, 45, 37, 63, 71, 0, 18],
                               [84, 45, 44, 35, 50, 80, 51, 60, 18, 0]])


antNum = 10                   # кол-во муравьев
alpha = 1                     # Фактор важности феромона
beta = 4                      # Фактор важности эвристической функции
pheEvaRate = 0.1              # Скорость испарения феромона
cityNum = distance_matrix_10.shape[0]
pheromone = np.ones((cityNum, cityNum))                   # Матрица феромонов
heuristic = 1 / (np.eye(cityNum) + distance_matrix_10) - np.eye(cityNum)       # Матрица эвристической информации
iter,itermax = 1, 100                       # Итерации

start_time = time.time()

while iter < itermax:
    antPath = np.zeros((antNum, cityNum)).astype(int) - 1   # Путь муравья
    firstCity = [i for i in range(10)]
    rd.shuffle(firstCity)          # Случайно назначьте начальный город для каждого муравья
    unvisted = []
    p = []
    pAccum = 0
    for i in range(len(antPath)):
        antPath[i][0] = firstCity[i]
    for i in range(len(antPath[0]) - 1):       # Постепенное обновление следующего города, в который собирается каждый муравей
        for j in range(len(antPath)):
            for k in range(cityNum):
                if k not in antPath[j]:
                    unvisted.append(k)
            for m in unvisted:
                pAccum += pheromone[antPath[j][i]][m] ** alpha * heuristic[antPath[j][i]][m] ** beta
            for n in unvisted:
                p.append(pheromone[antPath[j][i]][n] ** alpha * heuristic[antPath[j][i]][n] ** beta / pAccum)
            roulette = np.array(p).cumsum()               # Создать рулетку
            r = rd.uniform(min(roulette), max(roulette))
            for x in range(len(roulette)):
                if roulette[x] >= r:                      # Используйте метод рулетки, чтобы выбрать следующий город
                    antPath[j][i + 1] = unvisted[x]
                    break
            unvisted = []
            p = []
            pAccum = 0
    pheromone = (1 - pheEvaRate) * pheromone            # Феромон летучий
    length = lengthCal(antPath, distance_matrix_10)
    for i in range(len(antPath)):
        for j in range(len(antPath[i]) - 1):
            pheromone[antPath[i][j]][antPath[i][j + 1]] += 1 / length[i]     # Обновление феромона
        pheromone[antPath[i][-1]][antPath[i][0]] += 1 / length[i]
    iter += 1
print("Кратчайшее расстояние (в км): ")
print(min(length))
print("Самый короткий путь:")
print(antPath[length.index(min(length))])
print("Время выполнения:", (time.time() - start_time)) # вычисление времени выполнения

Кратчайшее расстояние (в км): 
350
Самый короткий путь:
[7 5 6 4 8 9 3 2 1 0]
Время выполнения: 0.6419622898101807


# Метод полного перебора

In [ ]:
pip install python-tsp

In [ ]:
from python_tsp.exact import solve_tsp_brute_force  # используем точный метод полного перебора


Для 5 городов

In [ ]:
distance_matrix_5 = np.array([[0, 38, 74, 59, 45],
                            [38, 0, 46, 61, 72],
                            [74, 46, 0, 49, 85],
                            [59, 61, 49, 0, 42],
                            [45, 72, 85, 42, 0]])

start_time = time.time()

path, distance = solve_tsp_brute_force(distance_matrix_5)

print("Кратчайшее расстояние (в км): ")
print(distance)

print("Самый короткий путь:")
print(path)

print("Время выполнения:")
print((time.time() - start_time))

Кратчайшее расстояние (в км): 
220
Самый короткий путь:
[0, 1, 2, 3, 4]
Время выполнения:
0.006056308746337891


Для 8 городов

In [ ]:
distance_matrix_8 = np.array([[0, 38, 74, 59, 45, 47, 90, 25],
                               [38, 0, 46, 61, 72, 50, 43, 51],
                               [74, 46, 0, 49, 85, 54, 59, 69],
                               [59, 61, 49, 0, 42, 35, 47, 56],
                               [45, 72, 85, 42, 0, 35, 47, 56],
                               [47, 50, 54, 35, 66, 0, 36, 44],
                               [90, 43, 59, 47, 35, 36, 0, 56],
                               [25, 51, 69, 56, 48, 44, 56, 0]])
start_time = time.time()

path, distance = solve_tsp_brute_force(distance_matrix_8)

print("Кратчайшее расстояние (в км): ")
print(distance)

print("Самый короткий путь:")
print(path)

print("Время выполнения:")
print((time.time() - start_time))

Кратчайшее расстояние (в км): 
315
Самый короткий путь:
[0, 7, 5, 6, 4, 3, 2, 1]
Время выполнения:
0.04943132400512695


Для 10 городов

In [ ]:
distance_matrix_10 = np.array([[0, 38, 74, 59, 45, 47, 90, 25, 67, 84],
                               [38, 0, 46, 61, 72, 50, 43, 51, 62, 45],
                               [74, 46, 0, 49, 85, 54, 59, 69, 40, 44],
                               [59, 61, 49, 0, 42, 35, 47, 56, 24, 35],
                               [45, 72, 85, 42, 0, 35, 47, 56, 24, 50],
                               [47, 50, 54, 35, 66, 0, 36, 44, 37, 80],
                               [90, 43, 59, 47, 35, 36, 0, 56, 63, 51],
                               [25, 51, 69, 56, 48, 44, 56, 0, 71, 60],
                               [67, 62, 70, 24, 45, 37, 63, 71, 0, 18],
                               [84, 45, 44, 35, 50, 80, 51, 60, 18, 0]])
start_time = time.time()

path, distance = solve_tsp_brute_force(distance_matrix_10)

print("Кратчайшее расстояние (в км): ")
print(distance)

print("Самый короткий путь:")
print(path)

print("Время выполнения:")
print((time.time() - start_time))

Кратчайшее расстояние (в км): 
350
Самый короткий путь:
[0, 7, 5, 6, 4, 8, 9, 3, 2, 1]
Время выполнения:
2.8411338329315186
